import {Color, Typeline} from "./Typeline";
import {Ability} from "./Ability";
import {ModificationLog} from "./ModificationLog";
import {Card, Counter} from "./Card";
import {capitalizeFirstLetter, deepCopy, getCssColor, joinList, shallowCopy} from "../Utilities";
import {Effect} from "./Effect";

export class Permanent {
    originalCard: Card;
    name: string;
    power: number;
    color: Color[];
    toughness: number;
    typeline: Typeline;
    controlledByOpponent: boolean;
    abilities: Ability[] = [];
    phasedOut: boolean;
    counters: Counter[] = [];
    ownedByOpponent : boolean = false;
    modificationLog: ModificationLog = new ModificationLog();
    timestamp: number;

    cssColor(): string {
        return getCssColor(this.color);
    }

    static fromCard(card: Card): Permanent {
        let p = new Permanent();
        p.originalCard = card;
        return p;
    }

    /**
     * Adds an ability to this permanent during a state check.
     * @param {Ability} ability The ability that's being add.
     * @param {Effect} source The effect that created the ability.
     */
    addAbility(ability: Ability, source : Effect) {
        ability.nonprinted = true;
        // 613.6a A continuous effect generated by a static ability has the same timestamp as the object the static ability is on, or the timestamp of the effect that created the ability, whichever is later.
        ability.effect.timestamp = Math.max(this.timestamp, source.timestamp);
        this.abilities.push(ability);
    }

    beginStateCheck(timestamp : number) {
        // Copy card
        this.name = this.originalCard.name;
        this.toughness = this.originalCard.toughness;
        this.power = this.originalCard.power;
        this.typeline = this.originalCard.typeline.copy();
        this.abilities = deepCopy(this.originalCard.abilities);
        this.color = shallowCopy(this.originalCard.color);
        // Blank status
        this.controlledByOpponent = this.ownedByOpponent;
        this.modificationLog = new ModificationLog();
        this.timestamp = timestamp;
        for (let ab of this.abilities) {
            ab.effect.source = this;
            ab.effect.acquisitionResults = null;
            ab.effect.timestamp = timestamp;
        }
    }
    describeColors() : string {
        let scolors : string[] = [];
        for (let clr of this.color) {
            scolors.push(Color[clr].toLowerCase());
        }
        return capitalizeFirstLetter(joinList(scolors));
    }
}